# Site
name: Evereal
description: Game Assets for VR, AR and Video
meta_description: Game Assets for VR, AR and Video
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'dev@evereal.com'
google_analytics: UA-134146948-5
disqus: eve-real

# Authors
authors:
  john:
    name: evereal
    display_name: Evereal
    image: /assets/images/logo.png
    email: dev@evereal.com
    web: evereal.com
    twitter:
    description: Hi, I am Evereal.

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/
  docs:
    output: true
    permalink: /docs/:path/

# Plugins
plugins:
  # - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username:
  card: summary

facebook:
  app_id:
  publisher: evereal.com
  admins:

social:
name: Evereal
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
